/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_management_system;

import DatabaseOperations.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author DELL
 */
public class NOCForm extends javax.swing.JFrame {

    String reg = "";

    /**
     * Creates new form NOCForm
     */
    public NOCForm() {
        initComponents();
        btNoc.setEnabled(false);
        btreturn.setEnabled(false);
        jLabel2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btreturn = new javax.swing.JButton();
        btNoc = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(240, 130));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Registration No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 29));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 70, 250, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1_search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookId", "Book Name", "Subject", "Registration", "Students Name", "Class Roll", "Issue Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 145, 899, 280));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 488, 836, -1));

        btreturn.setBackground(new java.awt.Color(0, 51, 102));
        btreturn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btreturn.setForeground(new java.awt.Color(255, 255, 255));
        btreturn.setText("Return Book");
        btreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 210, 50));

        btNoc.setBackground(new java.awt.Color(0, 51, 102));
        btNoc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btNoc.setForeground(new java.awt.Color(255, 255, 255));
        btNoc.setText("Generate NOC");
        btNoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNocActionPerformed(evt);
            }
        });
        getContentPane().add(btNoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 240, 50));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/favicon-32x32.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forallpages.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm1 = (DefaultTableModel) jTable1.getModel();
        dtm1.getDataVector().removeAllElements();
        String regno = jTextField1.getText();
        reg = regno;
        String query = "select * from student where registration='" + regno + "'";
        ArrayList<Student> lst = StudentDboperation.getRecordsOnCreteria(regno);
        Iterator<Student> it = lst.iterator();
        if (!it.hasNext()) {
            JOptionPane.showMessageDialog(this, "Enter valid registration no");
        } else {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            dtm.getDataVector().removeAllElements();
            ArrayList<IssueBook> list = IssueBookDbOperation.getAllRecordsOnCreteria(regno);
            int count = list.size();
            if (count == 0) {

                jLabel2.setText("Eligible for NOC Certificate");
                jLabel2.setForeground(Color.GREEN);
                btNoc.setEnabled(true);
            } else {
                Iterator<IssueBook> itr = list.iterator();
                while (itr.hasNext()) {
                    IssueBook bk = itr.next();
                    dtm.addRow(new Object[]{bk.getBookId(), bk.getBookName(), bk.getSubject(), bk.getRegirstration(), bk.getStudentName(), bk.getCollegeRoll(), bk.getIssueDate(), bk.getReturnDate()});
                }
                jLabel2.setText("Not Eligible for NOC certificate , Currenlty He has " + count + "   book.");
                jLabel2.setForeground(Color.red);

                btreturn.setEnabled(true);

            }

        }
        jButton1.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreturnActionPerformed
        this.dispose();
        new Return_Book().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btreturnActionPerformed

    private void btNocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNocActionPerformed
//        this.dispose();
        NocCertificate n = new NocCertificate();
        n.getReg(reg);
        n.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btNocActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new NOCForm().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NOCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NOCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NOCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NOCForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NOCForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNoc;
    private javax.swing.JButton btreturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
